### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'roles')

### ISSUE THREAD

**Issue by schblondie** [schblondie/gamebot#68]
at Object.execute (/home/container/interactions/modals/einwohnermeldeamt/ve2Reason.js:23:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.execute (/home/container/events/modalInteraction.js:34:9)
    at async Client.<anonymous> (/home/container/bot.js:47:26)

**Comment by schblondie** [comment]
Fixed in #83
